### ISSUE TITLE
SQL error : Upgrade from 0.83 to 0.90

### ISSUE THREAD

**Issue by tsmr** [pluginsGLPI/uninstall#2]
SQL error : 
```
2015-11-05 12:10:54 [2@P365]
  *** MySQL query error:
  SQL: ALTER TABLE `glpi_plugin_uninstall_profiles` CHANGE `ID` `id` INT(11) NOT NULL AUTO_INCREMENT  ,
CHANGE `use` `use` varchar(1) DEFAULT \'\'  ,
ADD `replace` TINYINT(1) NOT NULL DEFAULT \'0\'   
  Error: ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry '16' for key 'PRIMARY'
  Backtrace :
  inc\dbmysql.class.php:205                          
  inc\migration.class.php:579                        DBmysql->queryOrDie()
  plugins\uninstall\inc\profile.class.php:296        Migration->migrationOneTable()
  plugins\uninstall\hook.php:82                      PluginUninstallProfile::install()
  inc\plugin.class.php:643                           plugin_uninstall_install()
  :                                                  Plugin->install()
  front\plugin.form.php:49                           call_user_func()
```

**Comment by btry** [comment]
Is there a row with id = 0 ?

SELECT  count(*) FROM  `glpi_plugin_uninstall_profiles` WHERE `id`='0'

**Comment by tsmr** [comment]
Yes there is

**Comment by btry** [comment]
According to the source below, this id may may trigger the error

http://stackoverflow.com/questions/5402949/mysql-cant-make-column-auto-increment

This table is now useless due to the new right management in GLPI >= 0.85 . Can you change the id of this row and try again to upgrade ?

I also think there should not be any row with id = 0 in most tables. Do you confirm something has been tweaked in the past ?

**Comment by tsmr** [comment]
It's ok after drop this row.

But after upgrade the glpi_plugin_uninstall_profiles still exists

**Comment by btry** [comment]
#3 is for tracking progress about removal of this table on upgrade. Actually it is still created on install.
