### ISSUE TITLE
vulnerability Log4Shell?

### ISSUE THREAD

**Issue by FRANCOIS50** [pluginsGLPI/uninstall#56]
Glpi version 9.2.4
Plugin resources version 2.3.1
 
Good morning
I have a question:
Is the plugin vulnerable to Log4shell (CVE-2021-44228)?

Thank you in advance for your answer

Regards

**Comment by orthagh** [comment]
No GLPI and its plugins are not affected by Log4Shell vulnerability.

But 9.2 version is very old and we published [**a lot** of vulnerabilities](https://www.cvedetails.com/vulnerability-list/vendor_id-11461/product_id-21057/Glpi-project-Glpi.html) since its release
You should upgrade asap, not because log4shell, but because your glpi is vulnerable since years.
